### ISSUE TITLE
[Feat.Req] Watch mode

### ISSUE THREAD

**Issue by cargopete** [graphops/subgraph-radio#130]
**Problem statement**
We should add a cargo feature that enables us to run Subgraph Radio in "watch mode" where it matches all content topics (deployment hashes) in order to obtain a full view of the consensus state in the network. This way, we can fetch data from the metrics and the db (through the GraphQL API).

**Expectation proposal**
Watch mode should support the following:
- [ ] Shouldn't require Indexer mnemonic/pk or address to start up (afaik it shouldn't even require Graph Node endpoint?)
- [ ] Shouldn't send any messages
- [ ] Should match all incoming messages, regardless of content topic
