### ISSUE TITLE
Improve UpgradeIntentMessage

### ISSUE THREAD

**Issue by cargopete** [graphops/subgraph-radio#44]
- [x] ratelimit such that a given deployment only takes 1 upgrade (Issue link)
- [ ] allowlist, blocklist (Issue link)
- [ ] Check for signal - configurable minimal check

Document the potential attack on owner sending malicious messages can abuse indexers' resources, outline the capital needed by the owner to perform attacks
